use johnnyquest;

update teams set team = NULL;
delete from player_info;
delete from picks;
delete from games;
delete from filter;
delete from filter_link;
delete from scores;
delete from similarity_index;

INSERT into games (game, score, region, round, upset, winner) VALUES ('game_1','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_2','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_3','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_4','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_5','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_6','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_7','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_8','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_9','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_10','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_11','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_12','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_13','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_14','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_15','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_16','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_17','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_18','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_19','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_20','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_21','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_22','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_23','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_24','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_25','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_26','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_27','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_28','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_29','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_30','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_31','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_32','1',NULL,'1',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_33','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_34','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_35','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_36','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_37','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_38','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_39','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_40','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_41','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_42','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_43','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_44','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_45','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_46','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_47','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_48','2',NULL,'2',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_49','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_50','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_51','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_52','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_53','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_54','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_55','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_56','4',NULL,'3',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_57','6',NULL,'4',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_58','6',NULL,'4',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_59','6',NULL,'4',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_60','6',NULL,'4',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_61','8',NULL,'5',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_62','8',NULL,'5',NULL,NULL);
INSERT into games (game, score, region, round, upset, winner) VALUES ('game_63','16',NULL,'5',NULL,NULL);
